# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Obx < Formula
  desc "A CLI for your Oblax projects"
  homepage "oblax.io"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oblaxio/obx-cli-releases/releases/download/v0.0.1/obx_0.0.1_darwin_amd64.tar.gz"
      sha256 "ad99fa9c4a81d1b4465beba8e8e7d14f9154fde231ad8707c1c3799b4524feb3"

      def install
        bin.install "obx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oblaxio/obx-cli-releases/releases/download/v0.0.1/obx_0.0.1_darwin_arm64.tar.gz"
      sha256 "bd58a7e5c36d8b1b78ee7f780d265b87c1c2b17486131d2e35fad3b76704d0e8"

      def install
        bin.install "obx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/oblaxio/obx-cli-releases/releases/download/v0.0.1/obx_0.0.1_linux_amd64.tar.gz"
        sha256 "896380aa08a9e74bbe4440320f6c99485ecb5bcb09122923b5d885ec15f42554"

        def install
          bin.install "obx"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/oblaxio/obx-cli-releases/releases/download/v0.0.1/obx_0.0.1_linux_arm64.tar.gz"
        sha256 "d08e53d433c5b96487e6106e72b2b58dd89243d1c1622077fcfb67e0a5bbf1d3"

        def install
          bin.install "obx"
        end
      end
    end
  end
end
